name: dbt Slim CI for Snowflake Workspace

on:
  pull_request:
    branches: [ "main" ]

jobs:
  slim_ci:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - uses: actions/checkout@v4

      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade "pip<24"
          pip install "click==8.1.6"
          pip install "dbt-snowflake==1.9.1"

      # Use venv for dbt
      - name: dbt deps
        run: |
          source venv/bin/activate
          dbt deps --profiles-dir .github/profiles

      - name: dbt compile
        run: |
          source venv/bin/activate
          dbt compile --profiles-dir .github/profiles

      - name: Run modified models
        run: |
          source venv/bin/activate
          dbt run \
            --profiles-dir .github/profiles \
            --select state:modified+ \
            --state ./target

      - name: Test modified models
        run: |
          source venv/bin/activate
          dbt test \
            --profiles-dir .github/profiles \
            --select state:modified+ \
            --state ./target

      - name: dbt build
        run: |
          source venv/bin/activate
          dbt build \
            --profiles-dir .github/profiles \
            --select state:modified+ \
            --state ./target